export {
  default as AssessmentResult
} from './AssessmentResult/AssessmentResult'
export { default as Confidentiality } from './Confidentiality/Confidentiality'
export { default as Error } from './Error/Error'
export { default as Home } from './Home/Home'
export { default as HelpMyTeam } from './HelpMyTeam/HelpMyTeam'
export { default as NotFound } from './NotFound/NotFound'
export { default as OurTeam } from './OurTeam/OurTeam'
export { default as Privacy } from './Privacy/Privacy'
export { default as HowWeWork } from './HowWeWork/HowWeWork'
export { default as WhatWeDo } from './WhatWeDo/WhatWeDo'
export { default as IntroVideo } from './Video/IntroVideo'
export { default as SunVideo } from './Video/SunVideo'
export { default as IntroVideoKerri } from './Video/IntroVideoKerri'
