export { default as Header } from './Header/Header'
export { default as Footer } from './Footer/Footer'
export { default as Logo } from './Logo/Logo'
export { default as SocialLinks } from './SocialLinks/SocialLinks'
export { default as Template } from './Template/Template'
