export const ROUTE_CONFIDENTIALITY = '/confidentiality'
export const ROUTE_HELP_ME = '/help-me'
export const ROUTE_HELP_MY_TEAM = '/help-my-team'
export const ROUTE_HOME = '/'
export const ROUTE_OUR_TEAM = '/our-team'
export const ROUTE_PRIVACY = '/privacy'
