export { default as Header } from './Header/Header'
export { default as Footer } from './Footer/Footer'
export { default as Logo } from './Logo/Logo'
export { default as SelfAssessment } from './SelfAssessment/SelfAssessment'
export { default as Register } from './Register/Register'
export { default as ScrollToTop } from './ScrollToTop/ScrollToTop'
export { default as SocialLinks } from './SocialLinks/SocialLinks'
export { default as Template } from './Template/Template'
